services:
    vse.topicpreview.acp.controller:
        class: vse\topicpreview\controller\acp_controller
        arguments:
            - '@language'
            - '@request'
            - '@vse.topicpreview.settings'
            - '@template'

    vse.topicpreview.data:
        class: vse\topicpreview\core\data
        arguments:
            - '@config'
            - '@user'
            - '@dbal.conn'

    vse.topicpreview.display:
        class: vse\topicpreview\core\display
        arguments:
            - '@avatar.helper'
            - '@config'
            - '@dispatcher'
            - '@language'
            - '@template'
            - '@vse.topicpreview.renderer'
            - '@user'
            - '%core.root_path%'

    vse.topicpreview.renderer:
        class: vse\topicpreview\core\renderer
        arguments:
            - '@text_formatter.utils'

    vse.topicpreview.settings:
        class: vse\topicpreview\core\settings
        arguments:
            - '@cache.driver'
            - '@config'
            - '@dbal.conn'
            - '@ext.manager'
            - '@request'
            - '%core.root_path%'

# ----- Event Listeners -----
    vse.topicpreview.listener:
        class: vse\topicpreview\event\listener
        arguments:
            - '@vse.topicpreview.data'
            - '@vse.topicpreview.display'
        tags:
            - { name: event.listener }

    vse.topicpreview.ucp_listener:
        class: vse\topicpreview\event\ucp_listener
        arguments:
            - '@config'
            - '@language'
            - '@request'
            - '@template'
            - '@user'
        tags:
            - { name: event.listener }
